"""Auto-generated documentation from the live check registry.

Two outputs:
    docs/checks.md           — alphabetical catalog of every registered check.
    docs/standards-mapping.md — inverse: which standard clause maps to which checks.

These are intentionally machine-generated; the source of truth is the check
class metadata. Run `pdf-a11y gen-docs` to refresh them.
"""

from __future__ import annotations

from collections import defaultdict
from collections.abc import Iterable
from datetime import UTC, datetime
from pathlib import Path

from pdf_a11y import __version__
from pdf_a11y.checks import all_checks
from pdf_a11y.checks.base import Check
from pdf_a11y.models import Standard


def render_checks_md(checks: Iterable[Check]) -> str:
    checks = sorted(checks, key=lambda c: (c.category.value, c.id))
    by_category: dict[str, list[Check]] = defaultdict(list)
    for c in checks:
        by_category[c.category.value].append(c)

    out: list[str] = []
    out.append("# Check catalog")
    out.append("")
    out.append(
        f"Auto-generated from the registered check classes by `pdf-a11y gen-docs`. "
        f"Generated {datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')} from "
        f"pdf-a11y {__version__}."
    )
    out.append("")
    out.append(
        "Severity legend: **Critical** (10), **Major** (4), **Minor** (1), "
        "**Warning** (0). Detection: **machine** (deterministic), **heuristic** "
        "(may produce false positives — read evidence), **manual** (surfaced "
        "for human verification only)."
    )
    out.append("")
    out.append("## Summary")
    out.append("")
    total = sum(len(v) for v in by_category.values())
    out.append(f"- **Total registered checks:** {total}")
    for cat, items in sorted(by_category.items()):
        out.append(f"- **{cat}:** {len(items)}")
    out.append("")

    for cat, items in sorted(by_category.items()):
        out.append(f"## {cat}")
        out.append("")
        for c in items:
            out.append(f"### `{c.id}` — {c.name}")
            out.append("")
            out.append(
                f"- **Severity:** {c.severity.value} · "
                f"**Category:** {c.category.value} · "
                f"**Detection:** {c.detection.value}"
            )
            stds = ", ".join(_std_link(s) for s in c.standards) or "—"
            out.append(f"- **Standards:** {stds}")
            out.append("")
            if c.description:
                out.append(_md_paragraph(c.description))
                out.append("")
            if c.remediation:
                out.append(f"**Remediation.** {c.remediation}")
                out.append("")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def render_standards_mapping_md(checks: Iterable[Check]) -> str:
    checks = list(checks)
    # standard → clause → list of check ids
    by_std: dict[Standard, dict[str, list[str]]] = defaultdict(lambda: defaultdict(list))
    for c in checks:
        for s in c.standards:
            by_std[s.standard][s.clause].append(c.id)

    out: list[str] = []
    out.append("# Standards mapping")
    out.append("")
    out.append(
        f"Reverse index of every cited standard clause → the check(s) that "
        f"verify it. Auto-generated by `pdf-a11y gen-docs` from "
        f"pdf-a11y {__version__} on "
        f"{datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')}."
    )
    out.append("")
    out.append(
        "If you're remediating a document against a particular standard, look "
        "up the clauses below to find which `pdf-a11y` check IDs you'd expect "
        "to see in the report and which to filter for."
    )
    out.append("")

    for std in sorted(by_std, key=lambda s: s.value):
        out.append(f"## {std.value}")
        out.append("")
        out.append("| Clause | Verified by |")
        out.append("| --- | --- |")
        for clause in sorted(by_std[std]):
            ids = sorted(set(by_std[std][clause]))
            ids_str = ", ".join(f"`{i}`" for i in ids)
            out.append(f"| §{clause} | {ids_str} |")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def write_all(docs_dir: Path) -> tuple[Path, Path]:
    docs_dir.mkdir(parents=True, exist_ok=True)
    checks = all_checks()
    catalog_path = docs_dir / "checks.md"
    mapping_path = docs_dir / "standards-mapping.md"
    catalog_path.write_text(render_checks_md(checks), encoding="utf-8")
    mapping_path.write_text(render_standards_mapping_md(checks), encoding="utf-8")
    return catalog_path, mapping_path


def _std_link(s) -> str:  # type: ignore[no-untyped-def]
    label = f"{s.standard.value} §{s.clause}"
    if s.url:
        return f"[{label}]({s.url})"
    return label


def _md_paragraph(text: str) -> str:
    """Collapse internal whitespace and indent escapes."""
    return " ".join(text.split())


__all__ = ["render_checks_md", "render_standards_mapping_md", "write_all"]
